version: '3'

services:
  meu-mysql:
    build:
      context: ./MySQL
      dockerfile: mysql.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=senha+super+secreta
      #- MYSQL_DATABASE=Medidas
      - MYSQL_USER=app
      - MYSQL_PASSWORD=senha+super+secreta2
    #volumes: 
      #- ./MySQL:/usr/src
      #- ./MySQL/init-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - back-end
    
networks:
  back-end:
    driver: bridge