version: '3'

services:
  meu-mysql:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=senha+super+secreta
      - MYSQL_USER=app
      - MYSQL_PASSWORD=senha+super+secreta2
    volumes: 
     - MySQL-data:/var/lib/mysql
     - ./MySQL/init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - back-end
  
  app:
    build:
      context: ./app
      dockerfile: app.dockerfile
    volumes:
     - ./app/src:/usr/src/app/src
    depends_on:
      - meu-mysql
    environment:
      - DB_HOST=temperature-logger_meu-mysql_1
    networks:
      - back-end
    
networks:
  back-end:
    driver: bridge

volumes:
  MySQL-data:
    name: temperature-logger-mysql