version: '3'

services:
  meu-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=senha+super+secreta
      - MYSQL_DATABASE=Medidas
      - MYSQL_USER=app
      - MYSQL_PASSWORD=senha+super+secreta2
    volumes: 
      - ./MySQL:/usr/src
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - back-end
    
networks:
  back-end:
    driver: bridge