version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: db.dockerfile
    environment:
      #- POSTGRES_USER=app # Usar o usuário padrão "postgres"
      - POSTGRES_PASSWORD=senha+super+secreta
      - POSTGRES_DB="Medidas"
    volumes: 
     - ./db-data:/var/lib/postgresql/data
     #- ./db/init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3306:5432"
    networks:
      - back-end
  
  app:
    build:
      context: ./app
      dockerfile: app.dockerfile
    volumes:
     - ./app/src:/usr/src/app/src
     - ./app/logs:/usr/src/app/logs
    depends_on:
      - db
    environment:
      - DB_HOST=temperature-logger_db_1
      - DB_PORT=5432
    networks:
      - back-end
    
networks:
  back-end:
    driver: bridge

#volumes:
#  db-data:
#    name: temperature-logger-db